#!/usr/bin/env python3
"""
Script to visualize the pulsation mode data generated by probe_pulsation_modes.py
"""

import argparse
import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import cmasher as cmr
import numpy as np


def load_data(input_path):
    """Load the pickled data."""
    with open(input_path, 'rb') as f:
        data = pickle.load(f)
    return data


def plot_mode_comparison(data, output_dir=None):
    """Create comparison plots for all modes."""
    modes = data['modes']
    wavelengths = data['wavelengths']
    phases = data['phases']
    
    # Create colormap
    norm = plt.Normalize(phases.min(), phases.max())
    cmap = cmr.gem
    
    n_modes = len(modes)
    fig, axes = plt.subplots(n_modes, 1, figsize=(10, 4*n_modes), squeeze=False)
    
    for idx, (l, m) in enumerate(modes):
        ax = axes[idx, 0]
        spectra = data['spectra_by_mode'][(l, m)]['normalized']
        
        # Plot relative to first spectrum
        reference = spectra[0, :]
        
        for spec, phase in zip(spectra, phases):
            ax.plot(wavelengths, spec - reference, 
                   color=cmap(norm(phase)), alpha=0.5)
        
        ax.set_title(f'Mode l={l}, m={m}')
        ax.set_xlabel('Wavelength (Å)')
        ax.set_ylabel('Relative Flux')
        ax.grid(True, alpha=0.3)
    
    # Add colorbar
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array(phases)
    cbar = fig.colorbar(sm, ax=axes, label='Phase', aspect=40)
    
    plt.tight_layout()
    
    if output_dir:
        output_path = Path(output_dir) / 'mode_comparison.png'
        output_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"Saved comparison plot to: {output_path}")
    else:
        plt.show()
    
    plt.close()


def plot_line_profile_evolution(data, mode_idx=0, output_dir=None):
    """Plot the evolution of line profiles for a specific mode."""
    modes = data['modes']
    l, m = modes[mode_idx]
    
    wavelengths = data['wavelengths']
    phases = data['phases']
    spectra = data['spectra_by_mode'][(l, m)]['normalized']
    
    # Create colormap
    norm = plt.Normalize(phases.min(), phases.max())
    cmap = cmr.gem
    
    fig, ax = plt.subplots(figsize=(10, 6))
    
    reference = spectra[0, :]
    for spec, phase in zip(spectra, phases):
        ax.plot(wavelengths, spec / reference, 
               color=cmap(norm(phase)), alpha=0.6, linewidth=1)
    
    ax.set_title(f'Line Profile Evolution - Mode l={l}, m={m}')
    ax.set_xlabel('Wavelength (Å)')
    ax.set_ylabel('Normalized Flux')
    ax.grid(True, alpha=0.3)
    
    # Add colorbar
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array(phases)
    cbar = fig.colorbar(sm, ax=ax, label='Phase')
    
    plt.tight_layout()
    
    if output_dir:
        output_path = Path(output_dir) / f'line_evolution_l{l}_m{m}.png'
        output_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"Saved line evolution plot to: {output_path}")
    else:
        plt.show()
    
    plt.close()


def plot_line_core_zoom(data, wv_min=5499.5, wv_max=5500.5, output_dir=None):
    """Zoom into the line core for all modes."""
    modes = data['modes']
    wavelengths = data['wavelengths']
    phases = data['phases']
    
    # Find wavelength indices
    wv_mask = (wavelengths >= wv_min) & (wavelengths <= wv_max)
    wv_zoomed = wavelengths[wv_mask]
    
    # Create colormap
    norm = plt.Normalize(phases.min(), phases.max())
    cmap = cmr.gem
    
    n_modes = len(modes)
    fig, axes = plt.subplots(1, n_modes, figsize=(6*n_modes, 5), squeeze=False)
    
    for idx, (l, m) in enumerate(modes):
        ax = axes[0, idx]
        spectra = data['spectra_by_mode'][(l, m)]['normalized']
        
        # Plot relative to first spectrum
        reference = spectra[0, wv_mask]
        
        # Plot every few phases for clarity
        for spec, phase in zip(spectra[::2], phases[::2]):
            ax.plot(wv_zoomed, spec[wv_mask] - reference, 
                   color=cmap(norm(phase)), alpha=0.7, linewidth=1.5)
        
        ax.set_title(f'l={l}, m={m}')
        ax.set_xlabel('Wavelength (Å)')
        if idx == 0:
            ax.set_ylabel('Relative Flux')
        ax.grid(True, alpha=0.3)
    
    # Add colorbar
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array(phases)
    cbar = fig.colorbar(sm, ax=axes, label='Phase', aspect=20)
    
    plt.suptitle(f'Line Core Detail ({wv_min:.1f} - {wv_max:.1f} Å)', fontsize=14)
    plt.tight_layout()
    
    if output_dir:
        output_path = Path(output_dir) / 'line_core_zoom.png'
        output_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"Saved line core zoom to: {output_path}")
    else:
        plt.show()
    
    plt.close()


def print_data_summary(data):
    """Print a summary of the loaded data."""
    print("="*60)
    print("DATA SUMMARY")
    print("="*60)
    print(f"Number of modes: {len(data['modes'])}")
    print(f"Modes: {data['modes']}")
    print(f"Amplitude: {data['amplitude']}")
    print(f"Time steps: {len(data['timestamps'])}")
    print(f"Wavelength points: {len(data['wavelengths'])}")
    print(f"Wavelength range: {data['wavelengths'].min():.2f} - {data['wavelengths'].max():.2f} Å")
    print(f"Phase coverage: {data['phases'].min():.3f} - {data['phases'].max():.3f}")
    
    print("\nSpectra shapes:")
    for mode in data['modes']:
        shape = data['spectra_by_mode'][mode]['normalized'].shape
        print(f"  Mode {mode}: {shape}")
    print("="*60)


def main():
    parser = argparse.ArgumentParser(
        description='Visualize pulsation mode data'
    )
    parser.add_argument(
        'input',
        type=str,
        help='Input pickle file from probe_pulsation_modes.py'
    )
    parser.add_argument(
        '--output-dir',
        type=str,
        default=None,
        help='Output directory for plots (if not specified, plots are shown interactively)'
    )
    parser.add_argument(
        '--plots',
        type=str,
        nargs='+',
        default=['all'],
        choices=['all', 'comparison', 'evolution', 'zoom'],
        help='Which plots to generate (default: all)'
    )
    parser.add_argument(
        '--zoom-min',
        type=float,
        default=5499.5,
        help='Minimum wavelength for zoom plot (default: 5499.5)'
    )
    parser.add_argument(
        '--zoom-max',
        type=float,
        default=5500.5,
        help='Maximum wavelength for zoom plot (default: 5500.5)'
    )
    
    args = parser.parse_args()
    
    # Load data
    print(f"Loading data from: {args.input}")
    data = load_data(args.input)
    
    # Print summary
    print_data_summary(data)
    
    # Determine which plots to create
    plot_types = args.plots
    if 'all' in plot_types:
        plot_types = ['comparison', 'evolution', 'zoom']
    
    # Generate plots
    print("\nGenerating plots...")
    
    if 'comparison' in plot_types:
        print("  Creating mode comparison plot...")
        plot_mode_comparison(data, args.output_dir)
    
    if 'evolution' in plot_types:
        print("  Creating line profile evolution plot...")
        plot_line_profile_evolution(data, mode_idx=0, output_dir=args.output_dir)
    
    if 'zoom' in plot_types:
        print("  Creating line core zoom plot...")
        plot_line_core_zoom(data, args.zoom_min, args.zoom_max, args.output_dir)
    
    print("\nDone!")


if __name__ == '__main__':
    main()

